tmxrasterizer.exe --show-layer "Hor start-finish" --ignore-visibility C:\Users\johkarli\OneDrive\CommanderX16\Rallyworks\Tiled\Rallyblocks\rallyblocks.tmx C:\Users\johkarli\OneDrive\CommanderX16\Rallyworks\Tiled\Rallytracks\blocks\block0.png
tmxrasterizer.exe --show-layer "Hor road" --ignore-visibility C:\Users\johkarli\OneDrive\CommanderX16\Rallyworks\Tiled\Rallyblocks\rallyblocks.tmx C:\Users\johkarli\OneDrive\CommanderX16\Rallyworks\Tiled\Rallytracks\blocks\block1.png
tmxrasterizer.exe --show-layer "Hor road walled" --ignore-visibility C:\Users\johkarli\OneDrive\CommanderX16\Rallyworks\Tiled\Rallyblocks\rallyblocks.tmx C:\Users\johkarli\OneDrive\CommanderX16\Rallyworks\Tiled\Rallytracks\blocks\block2.png
tmxrasterizer.exe --show-layer "Hor road alle" --ignore-visibility C:\Users\johkarli\OneDrive\CommanderX16\Rallyworks\Tiled\Rallyblocks\rallyblocks.tmx C:\Users\johkarli\OneDrive\CommanderX16\Rallyworks\Tiled\Rallytracks\blocks\block3.png
tmxrasterizer.exe --show-layer "Hor road obstacle" --ignore-visibility C:\Users\johkarli\OneDrive\CommanderX16\Rallyworks\Tiled\Rallyblocks\rallyblocks.tmx C:\Users\johkarli\OneDrive\CommanderX16\Rallyworks\Tiled\Rallytracks\blocks\block4.png
tmxrasterizer.exe --show-layer "Hor road Q1 arrow" --ignore-visibility C:\Users\johkarli\OneDrive\CommanderX16\Rallyworks\Tiled\Rallyblocks\rallyblocks.tmx C:\Users\johkarli\OneDrive\CommanderX16\Rallyworks\Tiled\Rallytracks\blocks\block5.png
tmxrasterizer.exe --show-layer "Hor road Q2 arrow" --ignore-visibility C:\Users\johkarli\OneDrive\CommanderX16\Rallyworks\Tiled\Rallyblocks\rallyblocks.tmx C:\Users\johkarli\OneDrive\CommanderX16\Rallyworks\Tiled\Rallytracks\blocks\block6.png
tmxrasterizer.exe --show-layer "Hor road Q3 arrow" --ignore-visibility C:\Users\johkarli\OneDrive\CommanderX16\Rallyworks\Tiled\Rallyblocks\rallyblocks.tmx C:\Users\johkarli\OneDrive\CommanderX16\Rallyworks\Tiled\Rallytracks\blocks\block7.png
tmxrasterizer.exe --show-layer "Hor road Q4 arrow" --ignore-visibility C:\Users\johkarli\OneDrive\CommanderX16\Rallyworks\Tiled\Rallyblocks\rallyblocks.tmx C:\Users\johkarli\OneDrive\CommanderX16\Rallyworks\Tiled\Rallytracks\blocks\block8.png
tmxrasterizer.exe --show-layer "Hor chicane" --ignore-visibility C:\Users\johkarli\OneDrive\CommanderX16\Rallyworks\Tiled\Rallyblocks\rallyblocks.tmx C:\Users\johkarli\OneDrive\CommanderX16\Rallyworks\Tiled\Rallytracks\blocks\block9.png
tmxrasterizer.exe --show-layer "Hor road narrowing left" --ignore-visibility C:\Users\johkarli\OneDrive\CommanderX16\Rallyworks\Tiled\Rallyblocks\rallyblocks.tmx C:\Users\johkarli\OneDrive\CommanderX16\Rallyworks\Tiled\Rallytracks\blocks\block10.png
tmxrasterizer.exe --show-layer "Hor road narrowing right" --ignore-visibility C:\Users\johkarli\OneDrive\CommanderX16\Rallyworks\Tiled\Rallyblocks\rallyblocks.tmx C:\Users\johkarli\OneDrive\CommanderX16\Rallyworks\Tiled\Rallytracks\blocks\block11.png
tmxrasterizer.exe --show-layer "Hor stop left" --ignore-visibility C:\Users\johkarli\OneDrive\CommanderX16\Rallyworks\Tiled\Rallyblocks\rallyblocks.tmx C:\Users\johkarli\OneDrive\CommanderX16\Rallyworks\Tiled\Rallytracks\blocks\block12.png
tmxrasterizer.exe --show-layer "Hor stop right" --ignore-visibility C:\Users\johkarli\OneDrive\CommanderX16\Rallyworks\Tiled\Rallyblocks\rallyblocks.tmx C:\Users\johkarli\OneDrive\CommanderX16\Rallyworks\Tiled\Rallytracks\blocks\block13.png
tmxrasterizer.exe --show-layer "Ver start-finish" --ignore-visibility C:\Users\johkarli\OneDrive\CommanderX16\Rallyworks\Tiled\Rallyblocks\rallyblocks.tmx C:\Users\johkarli\OneDrive\CommanderX16\Rallyworks\Tiled\Rallytracks\blocks\block14.png
tmxrasterizer.exe --show-layer "Ver road" --ignore-visibility C:\Users\johkarli\OneDrive\CommanderX16\Rallyworks\Tiled\Rallyblocks\rallyblocks.tmx C:\Users\johkarli\OneDrive\CommanderX16\Rallyworks\Tiled\Rallytracks\blocks\block15.png
tmxrasterizer.exe --show-layer "Ver road walled" --ignore-visibility C:\Users\johkarli\OneDrive\CommanderX16\Rallyworks\Tiled\Rallyblocks\rallyblocks.tmx C:\Users\johkarli\OneDrive\CommanderX16\Rallyworks\Tiled\Rallytracks\blocks\block16.png
tmxrasterizer.exe --show-layer "Ver road alle" --ignore-visibility C:\Users\johkarli\OneDrive\CommanderX16\Rallyworks\Tiled\Rallyblocks\rallyblocks.tmx C:\Users\johkarli\OneDrive\CommanderX16\Rallyworks\Tiled\Rallytracks\blocks\block17.png
tmxrasterizer.exe --show-layer "Ver road obstacle" --ignore-visibility C:\Users\johkarli\OneDrive\CommanderX16\Rallyworks\Tiled\Rallyblocks\rallyblocks.tmx C:\Users\johkarli\OneDrive\CommanderX16\Rallyworks\Tiled\Rallytracks\blocks\block18.png
tmxrasterizer.exe --show-layer "Ver road Q1 arrow" --ignore-visibility C:\Users\johkarli\OneDrive\CommanderX16\Rallyworks\Tiled\Rallyblocks\rallyblocks.tmx C:\Users\johkarli\OneDrive\CommanderX16\Rallyworks\Tiled\Rallytracks\blocks\block19.png
tmxrasterizer.exe --show-layer "Ver road Q2 arrow" --ignore-visibility C:\Users\johkarli\OneDrive\CommanderX16\Rallyworks\Tiled\Rallyblocks\rallyblocks.tmx C:\Users\johkarli\OneDrive\CommanderX16\Rallyworks\Tiled\Rallytracks\blocks\block20.png
tmxrasterizer.exe --show-layer "Ver road Q3 arrow" --ignore-visibility C:\Users\johkarli\OneDrive\CommanderX16\Rallyworks\Tiled\Rallyblocks\rallyblocks.tmx C:\Users\johkarli\OneDrive\CommanderX16\Rallyworks\Tiled\Rallytracks\blocks\block21.png
tmxrasterizer.exe --show-layer "Ver road Q4 arrow" --ignore-visibility C:\Users\johkarli\OneDrive\CommanderX16\Rallyworks\Tiled\Rallyblocks\rallyblocks.tmx C:\Users\johkarli\OneDrive\CommanderX16\Rallyworks\Tiled\Rallytracks\blocks\block22.png
tmxrasterizer.exe --show-layer "Ver road chicane" --ignore-visibility C:\Users\johkarli\OneDrive\CommanderX16\Rallyworks\Tiled\Rallyblocks\rallyblocks.tmx C:\Users\johkarli\OneDrive\CommanderX16\Rallyworks\Tiled\Rallytracks\blocks\block23.png
tmxrasterizer.exe --show-layer "Ver road narrowing down" --ignore-visibility C:\Users\johkarli\OneDrive\CommanderX16\Rallyworks\Tiled\Rallyblocks\rallyblocks.tmx C:\Users\johkarli\OneDrive\CommanderX16\Rallyworks\Tiled\Rallytracks\blocks\block24.png
tmxrasterizer.exe --show-layer "Ver road narrowing up" --ignore-visibility C:\Users\johkarli\OneDrive\CommanderX16\Rallyworks\Tiled\Rallyblocks\rallyblocks.tmx C:\Users\johkarli\OneDrive\CommanderX16\Rallyworks\Tiled\Rallytracks\blocks\block25.png
tmxrasterizer.exe --show-layer "Ver stop up" --ignore-visibility C:\Users\johkarli\OneDrive\CommanderX16\Rallyworks\Tiled\Rallyblocks\rallyblocks.tmx C:\Users\johkarli\OneDrive\CommanderX16\Rallyworks\Tiled\Rallytracks\blocks\block26.png
tmxrasterizer.exe --show-layer "Ver stop down" --ignore-visibility C:\Users\johkarli\OneDrive\CommanderX16\Rallyworks\Tiled\Rallyblocks\rallyblocks.tmx C:\Users\johkarli\OneDrive\CommanderX16\Rallyworks\Tiled\Rallytracks\blocks\block27.png
tmxrasterizer.exe --show-layer "Narrow hor road" --ignore-visibility C:\Users\johkarli\OneDrive\CommanderX16\Rallyworks\Tiled\Rallyblocks\rallyblocks.tmx C:\Users\johkarli\OneDrive\CommanderX16\Rallyworks\Tiled\Rallytracks\blocks\block28.png
tmxrasterizer.exe --show-layer "Narrow ver road" --ignore-visibility C:\Users\johkarli\OneDrive\CommanderX16\Rallyworks\Tiled\Rallyblocks\rallyblocks.tmx C:\Users\johkarli\OneDrive\CommanderX16\Rallyworks\Tiled\Rallytracks\blocks\block29.png
tmxrasterizer.exe --show-layer "Narrow curve Q1" --ignore-visibility C:\Users\johkarli\OneDrive\CommanderX16\Rallyworks\Tiled\Rallyblocks\rallyblocks.tmx C:\Users\johkarli\OneDrive\CommanderX16\Rallyworks\Tiled\Rallytracks\blocks\block30.png
tmxrasterizer.exe --show-layer "Narrow curve Q2" --ignore-visibility C:\Users\johkarli\OneDrive\CommanderX16\Rallyworks\Tiled\Rallyblocks\rallyblocks.tmx C:\Users\johkarli\OneDrive\CommanderX16\Rallyworks\Tiled\Rallytracks\blocks\block31.png
tmxrasterizer.exe --show-layer "Narrow curve Q3" --ignore-visibility C:\Users\johkarli\OneDrive\CommanderX16\Rallyworks\Tiled\Rallyblocks\rallyblocks.tmx C:\Users\johkarli\OneDrive\CommanderX16\Rallyworks\Tiled\Rallytracks\blocks\block32.png
tmxrasterizer.exe --show-layer "Narrow curve Q4" --ignore-visibility C:\Users\johkarli\OneDrive\CommanderX16\Rallyworks\Tiled\Rallyblocks\rallyblocks.tmx C:\Users\johkarli\OneDrive\CommanderX16\Rallyworks\Tiled\Rallytracks\blocks\block33.png
tmxrasterizer.exe --show-layer "Narrow curve Q1 hor ext" --ignore-visibility C:\Users\johkarli\OneDrive\CommanderX16\Rallyworks\Tiled\Rallyblocks\rallyblocks.tmx C:\Users\johkarli\OneDrive\CommanderX16\Rallyworks\Tiled\Rallytracks\blocks\block34.png
tmxrasterizer.exe --show-layer "Narrow curve Q2 hor ext" --ignore-visibility C:\Users\johkarli\OneDrive\CommanderX16\Rallyworks\Tiled\Rallyblocks\rallyblocks.tmx C:\Users\johkarli\OneDrive\CommanderX16\Rallyworks\Tiled\Rallytracks\blocks\block35.png
tmxrasterizer.exe --show-layer "Narrow curve Q3 hor ext" --ignore-visibility C:\Users\johkarli\OneDrive\CommanderX16\Rallyworks\Tiled\Rallyblocks\rallyblocks.tmx C:\Users\johkarli\OneDrive\CommanderX16\Rallyworks\Tiled\Rallytracks\blocks\block36.png
tmxrasterizer.exe --show-layer "Narrow curve Q4 hor ext" --ignore-visibility C:\Users\johkarli\OneDrive\CommanderX16\Rallyworks\Tiled\Rallyblocks\rallyblocks.tmx C:\Users\johkarli\OneDrive\CommanderX16\Rallyworks\Tiled\Rallytracks\blocks\block37.png
tmxrasterizer.exe --show-layer "Narrow curve Q1 ver ext" --ignore-visibility C:\Users\johkarli\OneDrive\CommanderX16\Rallyworks\Tiled\Rallyblocks\rallyblocks.tmx C:\Users\johkarli\OneDrive\CommanderX16\Rallyworks\Tiled\Rallytracks\blocks\block38.png
tmxrasterizer.exe --show-layer "Narrow curve Q2 ver ext" --ignore-visibility C:\Users\johkarli\OneDrive\CommanderX16\Rallyworks\Tiled\Rallyblocks\rallyblocks.tmx C:\Users\johkarli\OneDrive\CommanderX16\Rallyworks\Tiled\Rallytracks\blocks\block39.png
tmxrasterizer.exe --show-layer "Narrow curve Q3 ver ext" --ignore-visibility C:\Users\johkarli\OneDrive\CommanderX16\Rallyworks\Tiled\Rallyblocks\rallyblocks.tmx C:\Users\johkarli\OneDrive\CommanderX16\Rallyworks\Tiled\Rallytracks\blocks\block40.png
tmxrasterizer.exe --show-layer "Narrow curve Q4 ver ext" --ignore-visibility C:\Users\johkarli\OneDrive\CommanderX16\Rallyworks\Tiled\Rallyblocks\rallyblocks.tmx C:\Users\johkarli\OneDrive\CommanderX16\Rallyworks\Tiled\Rallytracks\blocks\block41.png
tmxrasterizer.exe --show-layer "Curve Q1" --ignore-visibility C:\Users\johkarli\OneDrive\CommanderX16\Rallyworks\Tiled\Rallyblocks\rallyblocks.tmx C:\Users\johkarli\OneDrive\CommanderX16\Rallyworks\Tiled\Rallytracks\blocks\block42.png
tmxrasterizer.exe --show-layer "Curve Q2" --ignore-visibility C:\Users\johkarli\OneDrive\CommanderX16\Rallyworks\Tiled\Rallyblocks\rallyblocks.tmx C:\Users\johkarli\OneDrive\CommanderX16\Rallyworks\Tiled\Rallytracks\blocks\block43.png
tmxrasterizer.exe --show-layer "Curve Q3" --ignore-visibility C:\Users\johkarli\OneDrive\CommanderX16\Rallyworks\Tiled\Rallyblocks\rallyblocks.tmx C:\Users\johkarli\OneDrive\CommanderX16\Rallyworks\Tiled\Rallytracks\blocks\block44.png
tmxrasterizer.exe --show-layer "Curve Q4" --ignore-visibility C:\Users\johkarli\OneDrive\CommanderX16\Rallyworks\Tiled\Rallyblocks\rallyblocks.tmx C:\Users\johkarli\OneDrive\CommanderX16\Rallyworks\Tiled\Rallytracks\blocks\block45.png
tmxrasterizer.exe --show-layer "Curve Q1 hor ext arrow" --ignore-visibility C:\Users\johkarli\OneDrive\CommanderX16\Rallyworks\Tiled\Rallyblocks\rallyblocks.tmx C:\Users\johkarli\OneDrive\CommanderX16\Rallyworks\Tiled\Rallytracks\blocks\block46.png
tmxrasterizer.exe --show-layer "Curve Q1 hor ext" --ignore-visibility C:\Users\johkarli\OneDrive\CommanderX16\Rallyworks\Tiled\Rallyblocks\rallyblocks.tmx C:\Users\johkarli\OneDrive\CommanderX16\Rallyworks\Tiled\Rallytracks\blocks\block47.png
tmxrasterizer.exe --show-layer "Curve Q2 hor ext arrow" --ignore-visibility C:\Users\johkarli\OneDrive\CommanderX16\Rallyworks\Tiled\Rallyblocks\rallyblocks.tmx C:\Users\johkarli\OneDrive\CommanderX16\Rallyworks\Tiled\Rallytracks\blocks\block48.png
tmxrasterizer.exe --show-layer "Curve Q2 hor ext" --ignore-visibility C:\Users\johkarli\OneDrive\CommanderX16\Rallyworks\Tiled\Rallyblocks\rallyblocks.tmx C:\Users\johkarli\OneDrive\CommanderX16\Rallyworks\Tiled\Rallytracks\blocks\block49.png
tmxrasterizer.exe --show-layer "Curve Q3 hor ext arrow" --ignore-visibility C:\Users\johkarli\OneDrive\CommanderX16\Rallyworks\Tiled\Rallyblocks\rallyblocks.tmx C:\Users\johkarli\OneDrive\CommanderX16\Rallyworks\Tiled\Rallytracks\blocks\block50.png
tmxrasterizer.exe --show-layer "Curve Q3 hor ext" --ignore-visibility C:\Users\johkarli\OneDrive\CommanderX16\Rallyworks\Tiled\Rallyblocks\rallyblocks.tmx C:\Users\johkarli\OneDrive\CommanderX16\Rallyworks\Tiled\Rallytracks\blocks\block51.png
tmxrasterizer.exe --show-layer "Curve Q4 hor ext arrow" --ignore-visibility C:\Users\johkarli\OneDrive\CommanderX16\Rallyworks\Tiled\Rallyblocks\rallyblocks.tmx C:\Users\johkarli\OneDrive\CommanderX16\Rallyworks\Tiled\Rallytracks\blocks\block52.png
tmxrasterizer.exe --show-layer "Curve Q4 hor ext" --ignore-visibility C:\Users\johkarli\OneDrive\CommanderX16\Rallyworks\Tiled\Rallyblocks\rallyblocks.tmx C:\Users\johkarli\OneDrive\CommanderX16\Rallyworks\Tiled\Rallytracks\blocks\block53.png
tmxrasterizer.exe --show-layer "Curve Q1 ver ext arrow" --ignore-visibility C:\Users\johkarli\OneDrive\CommanderX16\Rallyworks\Tiled\Rallyblocks\rallyblocks.tmx C:\Users\johkarli\OneDrive\CommanderX16\Rallyworks\Tiled\Rallytracks\blocks\block54.png
tmxrasterizer.exe --show-layer "Curve Q1 ver ext" --ignore-visibility C:\Users\johkarli\OneDrive\CommanderX16\Rallyworks\Tiled\Rallyblocks\rallyblocks.tmx C:\Users\johkarli\OneDrive\CommanderX16\Rallyworks\Tiled\Rallytracks\blocks\block55.png
tmxrasterizer.exe --show-layer "Curve Q2 ver ext arrow" --ignore-visibility C:\Users\johkarli\OneDrive\CommanderX16\Rallyworks\Tiled\Rallyblocks\rallyblocks.tmx C:\Users\johkarli\OneDrive\CommanderX16\Rallyworks\Tiled\Rallytracks\blocks\block56.png
tmxrasterizer.exe --show-layer "Curve Q2 ver ext" --ignore-visibility C:\Users\johkarli\OneDrive\CommanderX16\Rallyworks\Tiled\Rallyblocks\rallyblocks.tmx C:\Users\johkarli\OneDrive\CommanderX16\Rallyworks\Tiled\Rallytracks\blocks\block57.png
tmxrasterizer.exe --show-layer "Curve Q3 ver ext arrow" --ignore-visibility C:\Users\johkarli\OneDrive\CommanderX16\Rallyworks\Tiled\Rallyblocks\rallyblocks.tmx C:\Users\johkarli\OneDrive\CommanderX16\Rallyworks\Tiled\Rallytracks\blocks\block58.png
tmxrasterizer.exe --show-layer "Curve Q3 ver ext" --ignore-visibility C:\Users\johkarli\OneDrive\CommanderX16\Rallyworks\Tiled\Rallyblocks\rallyblocks.tmx C:\Users\johkarli\OneDrive\CommanderX16\Rallyworks\Tiled\Rallytracks\blocks\block59.png
tmxrasterizer.exe --show-layer "Curve Q4 ver ext arrow" --ignore-visibility C:\Users\johkarli\OneDrive\CommanderX16\Rallyworks\Tiled\Rallyblocks\rallyblocks.tmx C:\Users\johkarli\OneDrive\CommanderX16\Rallyworks\Tiled\Rallytracks\blocks\block60.png
tmxrasterizer.exe --show-layer "Curve Q4 ver ext" --ignore-visibility C:\Users\johkarli\OneDrive\CommanderX16\Rallyworks\Tiled\Rallyblocks\rallyblocks.tmx C:\Users\johkarli\OneDrive\CommanderX16\Rallyworks\Tiled\Rallytracks\blocks\block61.png
tmxrasterizer.exe --show-layer "Curve Q3Q1 bridge" --ignore-visibility C:\Users\johkarli\OneDrive\CommanderX16\Rallyworks\Tiled\Rallyblocks\rallyblocks.tmx C:\Users\johkarli\OneDrive\CommanderX16\Rallyworks\Tiled\Rallytracks\blocks\block62.png
tmxrasterizer.exe --show-layer "Curve Q4Q2 bridge" --ignore-visibility C:\Users\johkarli\OneDrive\CommanderX16\Rallyworks\Tiled\Rallyblocks\rallyblocks.tmx C:\Users\johkarli\OneDrive\CommanderX16\Rallyworks\Tiled\Rallytracks\blocks\block63.png
tmxrasterizer.exe --show-layer "Curve Q1Q3 bridge" --ignore-visibility C:\Users\johkarli\OneDrive\CommanderX16\Rallyworks\Tiled\Rallyblocks\rallyblocks.tmx C:\Users\johkarli\OneDrive\CommanderX16\Rallyworks\Tiled\Rallytracks\blocks\block64.png
tmxrasterizer.exe --show-layer "Curve Q2Q4 bridge" --ignore-visibility C:\Users\johkarli\OneDrive\CommanderX16\Rallyworks\Tiled\Rallyblocks\rallyblocks.tmx C:\Users\johkarli\OneDrive\CommanderX16\Rallyworks\Tiled\Rallytracks\blocks\block65.png
tmxrasterizer.exe --show-layer "Curve Q1Q2 bridge" --ignore-visibility C:\Users\johkarli\OneDrive\CommanderX16\Rallyworks\Tiled\Rallyblocks\rallyblocks.tmx C:\Users\johkarli\OneDrive\CommanderX16\Rallyworks\Tiled\Rallytracks\blocks\block66.png
tmxrasterizer.exe --show-layer "Curve Q2Q3 bridge" --ignore-visibility C:\Users\johkarli\OneDrive\CommanderX16\Rallyworks\Tiled\Rallyblocks\rallyblocks.tmx C:\Users\johkarli\OneDrive\CommanderX16\Rallyworks\Tiled\Rallytracks\blocks\block67.png
tmxrasterizer.exe --show-layer "Curve Q3Q4 bridge" --ignore-visibility C:\Users\johkarli\OneDrive\CommanderX16\Rallyworks\Tiled\Rallyblocks\rallyblocks.tmx C:\Users\johkarli\OneDrive\CommanderX16\Rallyworks\Tiled\Rallytracks\blocks\block68.png
tmxrasterizer.exe --show-layer "Curve Q4Q1 bridge" --ignore-visibility C:\Users\johkarli\OneDrive\CommanderX16\Rallyworks\Tiled\Rallyblocks\rallyblocks.tmx C:\Users\johkarli\OneDrive\CommanderX16\Rallyworks\Tiled\Rallytracks\blocks\block69.png
tmxrasterizer.exe --show-layer "Crossing" --ignore-visibility C:\Users\johkarli\OneDrive\CommanderX16\Rallyworks\Tiled\Rallyblocks\rallyblocks.tmx C:\Users\johkarli\OneDrive\CommanderX16\Rallyworks\Tiled\Rallytracks\blocks\block70.png
tmxrasterizer.exe --show-layer "Crossing Q1 arrow 1" --ignore-visibility C:\Users\johkarli\OneDrive\CommanderX16\Rallyworks\Tiled\Rallyblocks\rallyblocks.tmx C:\Users\johkarli\OneDrive\CommanderX16\Rallyworks\Tiled\Rallytracks\blocks\block71.png
tmxrasterizer.exe --show-layer "Crossing Q1 arrow 2" --ignore-visibility C:\Users\johkarli\OneDrive\CommanderX16\Rallyworks\Tiled\Rallyblocks\rallyblocks.tmx C:\Users\johkarli\OneDrive\CommanderX16\Rallyworks\Tiled\Rallytracks\blocks\block72.png
tmxrasterizer.exe --show-layer "Crossing Q2 arrow 1" --ignore-visibility C:\Users\johkarli\OneDrive\CommanderX16\Rallyworks\Tiled\Rallyblocks\rallyblocks.tmx C:\Users\johkarli\OneDrive\CommanderX16\Rallyworks\Tiled\Rallytracks\blocks\block73.png
tmxrasterizer.exe --show-layer "Crossing Q2 arrow 2" --ignore-visibility C:\Users\johkarli\OneDrive\CommanderX16\Rallyworks\Tiled\Rallyblocks\rallyblocks.tmx C:\Users\johkarli\OneDrive\CommanderX16\Rallyworks\Tiled\Rallytracks\blocks\block74.png
tmxrasterizer.exe --show-layer "Crossing Q3 arrow 1" --ignore-visibility C:\Users\johkarli\OneDrive\CommanderX16\Rallyworks\Tiled\Rallyblocks\rallyblocks.tmx C:\Users\johkarli\OneDrive\CommanderX16\Rallyworks\Tiled\Rallytracks\blocks\block75.png
tmxrasterizer.exe --show-layer "Crossing Q3 arrow 2" --ignore-visibility C:\Users\johkarli\OneDrive\CommanderX16\Rallyworks\Tiled\Rallyblocks\rallyblocks.tmx C:\Users\johkarli\OneDrive\CommanderX16\Rallyworks\Tiled\Rallytracks\blocks\block76.png
tmxrasterizer.exe --show-layer "Crossing Q4 arrow 1" --ignore-visibility C:\Users\johkarli\OneDrive\CommanderX16\Rallyworks\Tiled\Rallyblocks\rallyblocks.tmx C:\Users\johkarli\OneDrive\CommanderX16\Rallyworks\Tiled\Rallytracks\blocks\block77.png
tmxrasterizer.exe --show-layer "Crossing Q4 arrow 2" --ignore-visibility C:\Users\johkarli\OneDrive\CommanderX16\Rallyworks\Tiled\Rallyblocks\rallyblocks.tmx C:\Users\johkarli\OneDrive\CommanderX16\Rallyworks\Tiled\Rallytracks\blocks\block78.png
tmxrasterizer.exe --show-layer "Crossing narrow" --ignore-visibility C:\Users\johkarli\OneDrive\CommanderX16\Rallyworks\Tiled\Rallyblocks\rallyblocks.tmx C:\Users\johkarli\OneDrive\CommanderX16\Rallyworks\Tiled\Rallytracks\blocks\block79.png
tmxrasterizer.exe --show-layer "Crossing narrow hor" --ignore-visibility C:\Users\johkarli\OneDrive\CommanderX16\Rallyworks\Tiled\Rallyblocks\rallyblocks.tmx C:\Users\johkarli\OneDrive\CommanderX16\Rallyworks\Tiled\Rallytracks\blocks\block80.png
tmxrasterizer.exe --show-layer "Crossing narrow ver" --ignore-visibility C:\Users\johkarli\OneDrive\CommanderX16\Rallyworks\Tiled\Rallyblocks\rallyblocks.tmx C:\Users\johkarli\OneDrive\CommanderX16\Rallyworks\Tiled\Rallytracks\blocks\block81.png
tmxrasterizer.exe --show-layer "T-junction up" --ignore-visibility C:\Users\johkarli\OneDrive\CommanderX16\Rallyworks\Tiled\Rallyblocks\rallyblocks.tmx C:\Users\johkarli\OneDrive\CommanderX16\Rallyworks\Tiled\Rallytracks\blocks\block82.png
tmxrasterizer.exe --show-layer "T-junction down" --ignore-visibility C:\Users\johkarli\OneDrive\CommanderX16\Rallyworks\Tiled\Rallyblocks\rallyblocks.tmx C:\Users\johkarli\OneDrive\CommanderX16\Rallyworks\Tiled\Rallytracks\blocks\block83.png
tmxrasterizer.exe --show-layer "T-junction left" --ignore-visibility C:\Users\johkarli\OneDrive\CommanderX16\Rallyworks\Tiled\Rallyblocks\rallyblocks.tmx C:\Users\johkarli\OneDrive\CommanderX16\Rallyworks\Tiled\Rallytracks\blocks\block84.png
tmxrasterizer.exe --show-layer "T-junction right" --ignore-visibility C:\Users\johkarli\OneDrive\CommanderX16\Rallyworks\Tiled\Rallyblocks\rallyblocks.tmx C:\Users\johkarli\OneDrive\CommanderX16\Rallyworks\Tiled\Rallytracks\blocks\block85.png
tmxrasterizer.exe --show-layer "T-junction up narrow" --ignore-visibility C:\Users\johkarli\OneDrive\CommanderX16\Rallyworks\Tiled\Rallyblocks\rallyblocks.tmx C:\Users\johkarli\OneDrive\CommanderX16\Rallyworks\Tiled\Rallytracks\blocks\block86.png
tmxrasterizer.exe --show-layer "T-junction down narrow" --ignore-visibility C:\Users\johkarli\OneDrive\CommanderX16\Rallyworks\Tiled\Rallyblocks\rallyblocks.tmx C:\Users\johkarli\OneDrive\CommanderX16\Rallyworks\Tiled\Rallytracks\blocks\block87.png
tmxrasterizer.exe --show-layer "T-junction left narrow" --ignore-visibility C:\Users\johkarli\OneDrive\CommanderX16\Rallyworks\Tiled\Rallyblocks\rallyblocks.tmx C:\Users\johkarli\OneDrive\CommanderX16\Rallyworks\Tiled\Rallytracks\blocks\block88.png
tmxrasterizer.exe --show-layer "T-junction right narrow" --ignore-visibility C:\Users\johkarli\OneDrive\CommanderX16\Rallyworks\Tiled\Rallyblocks\rallyblocks.tmx C:\Users\johkarli\OneDrive\CommanderX16\Rallyworks\Tiled\Rallytracks\blocks\block89.png
tmxrasterizer.exe --show-layer "Grass 1" --ignore-visibility C:\Users\johkarli\OneDrive\CommanderX16\Rallyworks\Tiled\Rallyblocks\rallyblocks.tmx C:\Users\johkarli\OneDrive\CommanderX16\Rallyworks\Tiled\Rallytracks\blocks\block90.png
tmxrasterizer.exe --show-layer "Grass 2" --ignore-visibility C:\Users\johkarli\OneDrive\CommanderX16\Rallyworks\Tiled\Rallyblocks\rallyblocks.tmx C:\Users\johkarli\OneDrive\CommanderX16\Rallyworks\Tiled\Rallytracks\blocks\block91.png
tmxrasterizer.exe --show-layer "Grass 3" --ignore-visibility C:\Users\johkarli\OneDrive\CommanderX16\Rallyworks\Tiled\Rallyblocks\rallyblocks.tmx C:\Users\johkarli\OneDrive\CommanderX16\Rallyworks\Tiled\Rallytracks\blocks\block92.png
tmxrasterizer.exe --show-layer "Trees 1" --ignore-visibility C:\Users\johkarli\OneDrive\CommanderX16\Rallyworks\Tiled\Rallyblocks\rallyblocks.tmx C:\Users\johkarli\OneDrive\CommanderX16\Rallyworks\Tiled\Rallytracks\blocks\block93.png
tmxrasterizer.exe --show-layer "Trees 2" --ignore-visibility C:\Users\johkarli\OneDrive\CommanderX16\Rallyworks\Tiled\Rallyblocks\rallyblocks.tmx C:\Users\johkarli\OneDrive\CommanderX16\Rallyworks\Tiled\Rallytracks\blocks\block94.png
tmxrasterizer.exe --show-layer "Farm 1" --ignore-visibility C:\Users\johkarli\OneDrive\CommanderX16\Rallyworks\Tiled\Rallyblocks\rallyblocks.tmx C:\Users\johkarli\OneDrive\CommanderX16\Rallyworks\Tiled\Rallytracks\blocks\block95.png
tmxrasterizer.exe --show-layer "Farm 2" --ignore-visibility C:\Users\johkarli\OneDrive\CommanderX16\Rallyworks\Tiled\Rallyblocks\rallyblocks.tmx C:\Users\johkarli\OneDrive\CommanderX16\Rallyworks\Tiled\Rallytracks\blocks\block96.png
tmxrasterizer.exe --show-layer "Farm 3" --ignore-visibility C:\Users\johkarli\OneDrive\CommanderX16\Rallyworks\Tiled\Rallyblocks\rallyblocks.tmx C:\Users\johkarli\OneDrive\CommanderX16\Rallyworks\Tiled\Rallytracks\blocks\block97.png
tmxrasterizer.exe --show-layer "Farm 4" --ignore-visibility C:\Users\johkarli\OneDrive\CommanderX16\Rallyworks\Tiled\Rallyblocks\rallyblocks.tmx C:\Users\johkarli\OneDrive\CommanderX16\Rallyworks\Tiled\Rallytracks\blocks\block98.png
tmxrasterizer.exe --show-layer "Barns 1" --ignore-visibility C:\Users\johkarli\OneDrive\CommanderX16\Rallyworks\Tiled\Rallyblocks\rallyblocks.tmx C:\Users\johkarli\OneDrive\CommanderX16\Rallyworks\Tiled\Rallytracks\blocks\block99.png
tmxrasterizer.exe --show-layer "Barns 2" --ignore-visibility C:\Users\johkarli\OneDrive\CommanderX16\Rallyworks\Tiled\Rallyblocks\rallyblocks.tmx C:\Users\johkarli\OneDrive\CommanderX16\Rallyworks\Tiled\Rallytracks\blocks\block100.png
tmxrasterizer.exe --show-layer "Forest 1" --ignore-visibility C:\Users\johkarli\OneDrive\CommanderX16\Rallyworks\Tiled\Rallyblocks\rallyblocks.tmx C:\Users\johkarli\OneDrive\CommanderX16\Rallyworks\Tiled\Rallytracks\blocks\block101.png
tmxrasterizer.exe --show-layer "Forest 2" --ignore-visibility C:\Users\johkarli\OneDrive\CommanderX16\Rallyworks\Tiled\Rallyblocks\rallyblocks.tmx C:\Users\johkarli\OneDrive\CommanderX16\Rallyworks\Tiled\Rallytracks\blocks\block102.png
tmxrasterizer.exe --show-layer "Forest 3" --ignore-visibility C:\Users\johkarli\OneDrive\CommanderX16\Rallyworks\Tiled\Rallyblocks\rallyblocks.tmx C:\Users\johkarli\OneDrive\CommanderX16\Rallyworks\Tiled\Rallytracks\blocks\block103.png
tmxrasterizer.exe --show-layer "Walls hor" --ignore-visibility C:\Users\johkarli\OneDrive\CommanderX16\Rallyworks\Tiled\Rallyblocks\rallyblocks.tmx C:\Users\johkarli\OneDrive\CommanderX16\Rallyworks\Tiled\Rallytracks\blocks\block104.png
tmxrasterizer.exe --show-layer "Walls ver" --ignore-visibility C:\Users\johkarli\OneDrive\CommanderX16\Rallyworks\Tiled\Rallyblocks\rallyblocks.tmx C:\Users\johkarli\OneDrive\CommanderX16\Rallyworks\Tiled\Rallytracks\blocks\block105.png
tmxrasterizer.exe --show-layer "Stones 1" --ignore-visibility C:\Users\johkarli\OneDrive\CommanderX16\Rallyworks\Tiled\Rallyblocks\rallyblocks.tmx C:\Users\johkarli\OneDrive\CommanderX16\Rallyworks\Tiled\Rallytracks\blocks\block106.png
tmxrasterizer.exe --show-layer "Stones 2" --ignore-visibility C:\Users\johkarli\OneDrive\CommanderX16\Rallyworks\Tiled\Rallyblocks\rallyblocks.tmx C:\Users\johkarli\OneDrive\CommanderX16\Rallyworks\Tiled\Rallytracks\blocks\block107.png
